# Generated by Django 3.1 on 2020-08-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='ip_address',
            field=models.CharField(default='None', max_length=50, unique=True),
        ),
    ]
