# Generated by Django 3.1 on 2020-08-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200808_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cplus_rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='candidate',
            name='dsa_rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='candidate',
            name='java_rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='candidate',
            name='python_rating',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
