# Generated by Django 2.2.13 on 2021-10-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200808_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='cplus_rating',
            new_name='backend',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='dsa_rating',
            new_name='devOps',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='java_rating',
            new_name='frontend',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='python_rating',
            new_name='fullstack',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='no_challenges_solved',
        ),
    ]
